apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetflix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetflix
  template:
    metadata:
      labels:
        app: kubernetflix
    spec:
      containers:
      - name: kubernetflix-container
        image: idanpersi/kubernetflix:lastest
        ports:
        - containerPort: 8010
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017